### ISSUE TITLE
Supporting wallet connect V2

### ISSUE THREAD

**Issue by Phelecks** [pingu2k4/blazor-web3modal#3]
Are you going to develop version 2 of wallet connect? You know current version going to shut down soon.

**Comment by pingu2k4** [comment]
I will be updating this to version 2 very shortly - its just 1 line of code change AFAIK. I need it for my own websites :P

**Comment by Phelecks** [comment]
Great news. Thank u so much

**Comment by pingu2k4** [comment]
Updated to WC V2 in fdabba3.

**Comment by Phelecks** [comment]
Well done dude. I download and test it and it works correctly. You will surprise me again with updating nuget package.

**Comment by pingu2k4** [comment]
Thats done now. Just waiting on Nuget to index the new version. :)
